# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 916d82aee5fe03d293382c88708bba8e31922bb1635a77205de254dfdf70c1ff5a85eb16a5a1da3a3b54f77a6f501a0d39adb423281b87e22080415204dd84be

test:
  secret_key_base: 924eefab2d465a8e35fb71cfe2576bc96d2065a03a73dcb07f25ac8bbbdb5bb2381a73a13f0e77bd836e4ccce19b0afc870405d2fe633817a1f65fbca3f92761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
